name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repoitory
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
                  cache: "yarn"

            - name: Setup Yarn
              uses: mskelton/setup-yarn@v1
              with:
                  node-version: "16.x"
                  flags: --immutable-cache

            - name: Build project
              run: yarn build

            - name: Upload production build files
              uses: actions/upload-artifact@v2
              with:
                  name: production-files
                  path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with: 
                name: production-files
                path: ./dist

            - name: Deploy to github pages
              uses: peaceiris/actions-gh-pages@v3
              with: 
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist  
